version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login registry.gitlab.com -u $DOCKER_USER_GITLAB -p $DOCKER_PASS_GITLAB
      - run: docker build -t registry.gitlab.com/$DOCKER_USER_GITLAB/biztoi_api_mock/$CIRCLE_BRANCH .
      - run: docker push registry.gitlab.com/$DOCKER_USER_GITLAB/biztoi_api_mock/$CIRCLE_BRANCH
